name: Build Libraries
run-name: Build Libraries
on: [push]

env:
  VERSION_NUMBER: 0.0.${{github.run_number}}

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
          protoc --version
      # Very important: versions the package.json node version which is the version that publish looks for 
      # in the github release we create next
      - name: NPM version v0.0.${{github.run_number}}
        working-directory: ts/apex-legends-liveapi
        run: |
          npm version $VERSION_NUMBER --git-tag-version false
      - name: Build Node Library
        working-directory: ts/apex-legends-liveapi
        run: |
          npm install
          npx tsc
      - name: Publish to npm
        working-directory: ts/apex-legends-liveapi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --access public
